# This file is an override and needs to be used in combination with docker-compose.yml like the following:
# docker-compose -f docker-compose.yml -f docker-compose-hosted.yml up
version: '3.7'

networks:
# Add Network for reverse-proxy
  reverse-proxy:
    name: reverse-proxy
    driver: bridge

volumes:
# Add volume for nginx-proxy and letsencrypt
  nginx-share:

services:

# Add Nginx reverse-proxy
# https://hub.docker.com/r/jwilder/nginx-proxy/
# Automated Nginx reverse proxy for docker containers
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-share:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html
      - ${PROXEUS_DATA_DIR:-./data}/certs:/etc/nginx/certs:ro
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
    networks:
      - reverse-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: unless-stopped

# Add Letsencrypt
# https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/
# LetsEncrypt container to use with nginx as proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    networks:
      - reverse-proxy
    volumes:
      - nginx-share:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html
      - ${PROXEUS_DATA_DIR:-./data}/certs:/etc/nginx/certs:rw
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    restart: unless-stopped

  platform:
    networks: 
      - reverse-proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
# Replace values for reverse-proxy
      VIRTUAL_HOST: proxeus.example.com
      VIRTUAL_PORT: 1323
# Replace values for letsencrypt
      LETSENCRYPT_HOST: proxeus.example.com
      LETSENCRYPT_EMAIL: admin@example.com

  document-service:
    networks: 
      - reverse-proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
# Replace values for reverse-proxy
      VIRTUAL_HOST: proxeus.example.com
      VIRTUAL_PORT: 2115
# Replace values for letsencrypt
      LETSENCRYPT_HOST: proxeus.example.com
      LETSENCRYPT_EMAIL: admin@example.com

# Add Watchtower
# https://hub.docker.com/r/v2tec/watchtower/
# Watches your containers and automatically restarts them whenever their image is refreshed
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ${DOCKER_CONFIG_FILE:-/root/.docker/config.json}:/config.json
    command: --interval 60 --label-enable
