---
version: "3.7"

networks:
  xes-platform-network:
    name: xes-platform-network

services:
  mongo0:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    command: "--bind_ip_all --replSet rs0"
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ${PWD}/mongo-replica.js:/docker-entrypoint-initdb.d/mongo-replica.js

  mongo1:
    image: mongo:latest
    ports:
      - 27018:27018
    restart: unless-stopped
    command: "--bind_ip_all --replSet rs0 --port 27018"

  mongo2:
    image: mongo:latest
    ports:
      - 27019:27019
    restart: unless-stopped
    command: "--bind_ip_all --replSet rs0 --port 27019"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo0,mongo1:28017,mongo2:27019
