---
# Here we show how to configure all the extra nodes with default settings.
# This file is an override and needs to be used like this:
#
#  docker-compose -f docker-compose.yml -f docker-compose-extra.override.yml up

version: '3.7'

services:
  node-mail-sender:
    image: proxeus/node-mail-sender:latest
    container_name: xes_node-mail-sender
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8013
      SERVICE_URL: "${NODE_CRYPTO_RATES_URL:-http://node-mail-sender:8013}"
      TZ: Europe/Zurich
      PROXEUS_SPARKPOST_API_KEY: "${PROXEUS_SPARKPOST_API_KEY}"
    ports:
      - "8013:8013"

  node-crypto-forex-rates:
    image: proxeus/node-crypto-forex-rates:latest
    container_name: xes_node-crypto-forex-rates
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8011
      SERVICE_URL: "${NODE_CRYPTO_RATES_URL:-http://node-crypto-forex-rates:8011}"
      TZ: Europe/Zurich
    ports:
      - "8011:8011"

  node-balance-retriever:
    image: proxeus/node-balance-retriever:latest
    container_name: xes_node-node-balance-retriever
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      PROXEUS_ETH_CLIENT_URL: "${PROXEUS_ETH_CLIENT_URL:-https://sepolia.infura.io/v3/}"
      PROXEUS_INFURA_API_KEY: ${PROXEUS_INFURA_API_KEY}
      SERVICE_SECRET: secret
      SERVICE_PORT: 8012
      SERVICE_URL: "${NODE_BALANCE_RETRIEVER_URL:-http://node-balance-retriever:8012}"
      TZ: Europe/Zurich
    ports:
      - "8012:8012"

  node-proof-of-existence:
    image: proxeus/node-proof-of-existence:latest
    container_name: xes_node-proof-of-existence
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8014
      SERVICE_URL: "${SERVICE_DOMAIN:-http://node-proof-of-existence:8014}"
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TZ: Europe/Zurich
    ports:
      - "8014:8014"

  node-json-sender:
    image: proxeus/node-json-sender:latest
    container_name: xes_node-json-sender
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8015
      SERVICE_URL: "${SERVICE_DOMAIN:-http://node-json-sender:8015}"
      JSON_SENDER_URL: http://url:123/endpoint
      JSON_SENDER_HEADER_clientid: client_id
      JSON_SENDER_HEADER_tenantid: tenant_id
      JSON_SENDER_HEADER_secret: secret
      JSON_SENDER_HEADER_oauthserverurl: oauth_url
      TZ: Europe/Zurich
    ports:
      - "8015:8015"
