---
# Slim version of the Docker Compose cloud deployment

version: '3.7'

networks:
  xes-platform-network:
    name: xes-platform-network
  reverse-proxy:
    name: reverse-proxy
    driver: bridge

services:
  platform:
    build:
      context: .
    container_name: xes-platform
    depends_on:
      - document-service
    networks:
      - xes-platform-network
      - reverse-proxy
    restart: unless-stopped
    environment:
      TZ: Europe/Zurich
      PROXEUS_PLATFORM_DOMAIN: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      PROXEUS_DOCUMENT_SERVICE_URL: "http://document-service:2115/"
      PROXEUS_BLOCKCHAIN_CONTRACT_ADDRESS: "${PROXEUS_BLOCKCHAIN_CONTRACT_ADDRESS}"
      PROXEUS_INFURA_API_KEY: "${PROXEUS_INFURA_API_KEY}"
      PROXEUS_SPARKPOST_API_KEY: "${PROXEUS_SPARKPOST_API_KEY}"
      PROXEUS_ENCRYPTION_SECRET_KEY: "${PROXEUS_ENCRYPTION_SECRET_KEY}"
      PROXEUS_EMAIL_FROM: "${PROXEUS_EMAIL_FROM:-no-reply@example.com}"
      PROXEUS_DATABASE_ENGINE: "${PROXEUS_DATABASE_ENGINE:-storm}"
      PROXEUS_DATABASE_URI: "${PROXEUS_DATABASE_URI:-mongodb://root:root@mongo:27017}"
      PROXEUS_TEST_MODE: "${PROXEUS_TEST_MODE:-false}"
      PROXEUS_ALLOW_HTTP: "${PROXEUS_ALLOW_HTTP:-true}"
      # Replace values for reverse-proxy
      VIRTUAL_HOST: ${PROXEUS_VIRTUAL_HOST:-proxeus.example.com}
      VIRTUAL_PORT: 1323
      # Replace values for letsencrypt
      LETSENCRYPT_HOST: ${PROXEUS_VIRTUAL_HOST:-proxeus.example.com}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-admin@proxeus.example.com}
    ports:
      - "1323:1323"
    volumes:
      - ${PROXEUS_DATA_DIR:-./data}/proxeus-platform/data:/data/hosted
      - ${PROXEUS_DATA_DIR:-./data}/proxeus-platform/settings:/root/.proxeus/settings

  # Add Nginx reverse-proxy
  # https://hub.docker.com/r/jwilder/nginx-proxy/
  # Automated Nginx reverse proxy for docker containers
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-share:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html
      - ./nginx-timeout.conf:/etc/nginx/conf.d/nginx-timeout.conf
      - ${PROXEUS_DATA_DIR:-./data}/certs:/etc/nginx/certs:ro
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
    networks:
      - reverse-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: unless-stopped

  # Add Letsencrypt
  # https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/
  # LetsEncrypt container to use with nginx as proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    networks:
      - reverse-proxy
    volumes:
      - nginx-share:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html
      - ${PROXEUS_DATA_DIR:-./data}/certs:/etc/nginx/certs:rw
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    restart: unless-stopped
    
  document-service:
    image: proxeus/document-service:latest
    container_name: xes_document_service
    networks:
      - xes-platform-network
      - reverse-proxy
    restart: unless-stopped
    environment:
      TZ: Europe/Zurich
      # Replace values for reverse-proxy
      VIRTUAL_HOST: ${DOCUMENT_SERVICE_VIRTUAL_HOST:-proxeus.example.com}
      VIRTUAL_PORT: 2115
      # Replace values for letsencrypt
      LETSENCRYPT_HOST: ${DOCUMENT_SERVICE_VIRTUAL_HOST:-proxeus.example.com}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-admin@example.com}
    ports:
      - "2115:2115"
    volumes:
      - ${PROXEUS_DATA_DIR:-./data}/document-service/logs:/document-service/logs
      - ${PROXEUS_DATA_DIR:-./data}/document-service/fonts:/document-service/fonts

  node-mail-sender:
    image: proxeus/node-mail-sender:latest
    container_name: xes_node-mail-sender
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8013
      SERVICE_URL: "${NODE_CRYPTO_RATES_URL:-http://node-mail-sender:8013}"
      TZ: Europe/Zurich
      PROXEUS_SPARKPOST_API_KEY: "${PROXEUS_SPARKPOST_API_KEY}"
    ports:
      - "8013:8013"

  node-json-sender:
    image: proxeus/node-json-sender:latest
    container_name: xes_node-json-sender
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: "${PROXEUS_PLATFORM_DOMAIN:-http://xes-platform:1323}"
      SERVICE_SECRET: secret
      SERVICE_PORT: 8015
      SERVICE_URL: "${SERVICE_DOMAIN:-http://node-json-sender:8015}"
      JSON_SENDER_URL: http://url:123/endpoint
      JSON_SENDER_HEADER_clientid: client_id
      JSON_SENDER_HEADER_tenantid: tenant_id
      JSON_SENDER_HEADER_secret: secret
      JSON_SENDER_HEADER_oauthserverurl: oauth_url
      TZ: Europe/Zurich
    ports:
      - "8015:8015"

volumes:
  # Add volume for nginx-proxy and letsencrypt
  nginx-share:
  
