// Code generated by MockGen. DO NOT EDIT.
// Source: storage/interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	externalnode "github.com/ProxeusApp/proxeus-core/externalnode"
	storage "github.com/ProxeusApp/proxeus-core/storage"
	file "github.com/ProxeusApp/proxeus-core/sys/file"
	model "github.com/ProxeusApp/proxeus-core/sys/model"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
	time "time"
)

// MockSettingsIF is a mock of SettingsIF interface
type MockSettingsIF struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsIFMockRecorder
}

// MockSettingsIFMockRecorder is the mock recorder for MockSettingsIF
type MockSettingsIFMockRecorder struct {
	mock *MockSettingsIF
}

// NewMockSettingsIF creates a new mock instance
func NewMockSettingsIF(ctrl *gomock.Controller) *MockSettingsIF {
	mock := &MockSettingsIF{ctrl: ctrl}
	mock.recorder = &MockSettingsIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSettingsIF) EXPECT() *MockSettingsIFMockRecorder {
	return m.recorder
}

// Put mocks base method
func (m *MockSettingsIF) Put(stngs *model.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", stngs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockSettingsIFMockRecorder) Put(stngs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSettingsIF)(nil).Put), stngs)
}

// Get mocks base method
func (m *MockSettingsIF) Get() (*model.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*model.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockSettingsIFMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingsIF)(nil).Get))
}

// Close mocks base method
func (m *MockSettingsIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSettingsIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSettingsIF)(nil).Close))
}

// MockI18nIF is a mock of I18nIF interface
type MockI18nIF struct {
	ctrl     *gomock.Controller
	recorder *MockI18nIFMockRecorder
}

// MockI18nIFMockRecorder is the mock recorder for MockI18nIF
type MockI18nIFMockRecorder struct {
	mock *MockI18nIF
}

// NewMockI18nIF creates a new mock instance
func NewMockI18nIF(ctrl *gomock.Controller) *MockI18nIF {
	mock := &MockI18nIF{ctrl: ctrl}
	mock.recorder = &MockI18nIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockI18nIF) EXPECT() *MockI18nIFMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockI18nIF) Find(keyContains, valueContains string, options storage.Options) (map[string]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", keyContains, valueContains, options)
	ret0, _ := ret[0].(map[string]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockI18nIFMockRecorder) Find(keyContains, valueContains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockI18nIF)(nil).Find), keyContains, valueContains, options)
}

// Get mocks base method
func (m *MockI18nIF) Get(lang, key string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{lang, key}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockI18nIFMockRecorder) Get(lang, key interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{lang, key}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockI18nIF)(nil).Get), varargs...)
}

// GetAll mocks base method
func (m *MockI18nIF) GetAll(lang string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", lang)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockI18nIFMockRecorder) GetAll(lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockI18nIF)(nil).GetAll), lang)
}

// PutAll mocks base method
func (m *MockI18nIF) PutAll(lang string, translations map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutAll", lang, translations)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutAll indicates an expected call of PutAll
func (mr *MockI18nIFMockRecorder) PutAll(lang, translations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAll", reflect.TypeOf((*MockI18nIF)(nil).PutAll), lang, translations)
}

// Put mocks base method
func (m *MockI18nIF) Put(lang, key, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", lang, key, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockI18nIFMockRecorder) Put(lang, key, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockI18nIF)(nil).Put), lang, key, text)
}

// PutLang mocks base method
func (m *MockI18nIF) PutLang(lang string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutLang", lang, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutLang indicates an expected call of PutLang
func (mr *MockI18nIFMockRecorder) PutLang(lang, enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLang", reflect.TypeOf((*MockI18nIF)(nil).PutLang), lang, enabled)
}

// GetLangs mocks base method
func (m *MockI18nIF) GetLangs(enabled bool) ([]*model.Lang, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLangs", enabled)
	ret0, _ := ret[0].([]*model.Lang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLangs indicates an expected call of GetLangs
func (mr *MockI18nIFMockRecorder) GetLangs(enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLangs", reflect.TypeOf((*MockI18nIF)(nil).GetLangs), enabled)
}

// HasLang mocks base method
func (m *MockI18nIF) HasLang(lang string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasLang", lang)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasLang indicates an expected call of HasLang
func (mr *MockI18nIFMockRecorder) HasLang(lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasLang", reflect.TypeOf((*MockI18nIF)(nil).HasLang), lang)
}

// GetAllLangs mocks base method
func (m *MockI18nIF) GetAllLangs() ([]*model.Lang, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLangs")
	ret0, _ := ret[0].([]*model.Lang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLangs indicates an expected call of GetAllLangs
func (mr *MockI18nIFMockRecorder) GetAllLangs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLangs", reflect.TypeOf((*MockI18nIF)(nil).GetAllLangs))
}

// PutFallback mocks base method
func (m *MockI18nIF) PutFallback(lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFallback", lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutFallback indicates an expected call of PutFallback
func (mr *MockI18nIFMockRecorder) PutFallback(lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFallback", reflect.TypeOf((*MockI18nIF)(nil).PutFallback), lang)
}

// GetFallback mocks base method
func (m *MockI18nIF) GetFallback() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFallback")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFallback indicates an expected call of GetFallback
func (mr *MockI18nIFMockRecorder) GetFallback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFallback", reflect.TypeOf((*MockI18nIF)(nil).GetFallback))
}

// Close mocks base method
func (m *MockI18nIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockI18nIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockI18nIF)(nil).Close))
}

// MockFormIF is a mock of FormIF interface
type MockFormIF struct {
	ctrl     *gomock.Controller
	recorder *MockFormIFMockRecorder
}

// MockFormIFMockRecorder is the mock recorder for MockFormIF
type MockFormIFMockRecorder struct {
	mock *MockFormIF
}

// NewMockFormIF creates a new mock instance
func NewMockFormIF(ctrl *gomock.Controller) *MockFormIF {
	mock := &MockFormIF{ctrl: ctrl}
	mock.recorder = &MockFormIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFormIF) EXPECT() *MockFormIFMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockFormIF) List(auth model.Auth, contains string, options storage.Options) ([]*model.FormItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", auth, contains, options)
	ret0, _ := ret[0].([]*model.FormItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockFormIFMockRecorder) List(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFormIF)(nil).List), auth, contains, options)
}

// Get mocks base method
func (m *MockFormIF) Get(auth model.Auth, id string) (*model.FormItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", auth, id)
	ret0, _ := ret[0].(*model.FormItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockFormIFMockRecorder) Get(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFormIF)(nil).Get), auth, id)
}

// Put mocks base method
func (m *MockFormIF) Put(auth model.Auth, item *model.FormItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", auth, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockFormIFMockRecorder) Put(auth, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockFormIF)(nil).Put), auth, item)
}

// Delete mocks base method
func (m *MockFormIF) Delete(auth model.Auth, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", auth, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockFormIFMockRecorder) Delete(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFormIF)(nil).Delete), auth, id)
}

// DelComp mocks base method
func (m *MockFormIF) DelComp(auth model.Auth, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelComp", auth, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelComp indicates an expected call of DelComp
func (mr *MockFormIFMockRecorder) DelComp(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelComp", reflect.TypeOf((*MockFormIF)(nil).DelComp), auth, id)
}

// PutComp mocks base method
func (m *MockFormIF) PutComp(auth model.Auth, comp *model.FormComponentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutComp", auth, comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutComp indicates an expected call of PutComp
func (mr *MockFormIFMockRecorder) PutComp(auth, comp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutComp", reflect.TypeOf((*MockFormIF)(nil).PutComp), auth, comp)
}

// GetComp mocks base method
func (m *MockFormIF) GetComp(auth model.Auth, id string) (*model.FormComponentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComp", auth, id)
	ret0, _ := ret[0].(*model.FormComponentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComp indicates an expected call of GetComp
func (mr *MockFormIFMockRecorder) GetComp(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComp", reflect.TypeOf((*MockFormIF)(nil).GetComp), auth, id)
}

// ListComp mocks base method
func (m *MockFormIF) ListComp(auth model.Auth, contains string, options storage.Options) (map[string]*model.FormComponentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComp", auth, contains, options)
	ret0, _ := ret[0].(map[string]*model.FormComponentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComp indicates an expected call of ListComp
func (mr *MockFormIFMockRecorder) ListComp(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComp", reflect.TypeOf((*MockFormIF)(nil).ListComp), auth, contains, options)
}

// Vars mocks base method
func (m *MockFormIF) Vars(auth model.Auth, contains string, options storage.Options) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vars", auth, contains, options)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vars indicates an expected call of Vars
func (mr *MockFormIFMockRecorder) Vars(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vars", reflect.TypeOf((*MockFormIF)(nil).Vars), auth, contains, options)
}

// Close mocks base method
func (m *MockFormIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockFormIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFormIF)(nil).Close))
}

// MockWorkflowIF is a mock of WorkflowIF interface
type MockWorkflowIF struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowIFMockRecorder
}

// MockWorkflowIFMockRecorder is the mock recorder for MockWorkflowIF
type MockWorkflowIFMockRecorder struct {
	mock *MockWorkflowIF
}

// NewMockWorkflowIF creates a new mock instance
func NewMockWorkflowIF(ctrl *gomock.Controller) *MockWorkflowIF {
	mock := &MockWorkflowIF{ctrl: ctrl}
	mock.recorder = &MockWorkflowIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkflowIF) EXPECT() *MockWorkflowIFMockRecorder {
	return m.recorder
}

// ListPublished mocks base method
func (m *MockWorkflowIF) ListPublished(auth model.Auth, contains string, options storage.Options) ([]*model.WorkflowItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublished", auth, contains, options)
	ret0, _ := ret[0].([]*model.WorkflowItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublished indicates an expected call of ListPublished
func (mr *MockWorkflowIFMockRecorder) ListPublished(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublished", reflect.TypeOf((*MockWorkflowIF)(nil).ListPublished), auth, contains, options)
}

// List mocks base method
func (m *MockWorkflowIF) List(auth model.Auth, contains string, options storage.Options) ([]*model.WorkflowItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", auth, contains, options)
	ret0, _ := ret[0].([]*model.WorkflowItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockWorkflowIFMockRecorder) List(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowIF)(nil).List), auth, contains, options)
}

// GetPublished mocks base method
func (m *MockWorkflowIF) GetPublished(auth model.Auth, id string) (*model.WorkflowItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublished", auth, id)
	ret0, _ := ret[0].(*model.WorkflowItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublished indicates an expected call of GetPublished
func (mr *MockWorkflowIFMockRecorder) GetPublished(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublished", reflect.TypeOf((*MockWorkflowIF)(nil).GetPublished), auth, id)
}

// Get mocks base method
func (m *MockWorkflowIF) Get(auth model.Auth, id string) (*model.WorkflowItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", auth, id)
	ret0, _ := ret[0].(*model.WorkflowItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockWorkflowIFMockRecorder) Get(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkflowIF)(nil).Get), auth, id)
}

// GetList mocks base method
func (m *MockWorkflowIF) GetList(auth model.Auth, id []string) ([]*model.WorkflowItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", auth, id)
	ret0, _ := ret[0].([]*model.WorkflowItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList
func (mr *MockWorkflowIFMockRecorder) GetList(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockWorkflowIF)(nil).GetList), auth, id)
}

// Put mocks base method
func (m *MockWorkflowIF) Put(auth model.Auth, item *model.WorkflowItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", auth, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockWorkflowIFMockRecorder) Put(auth, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockWorkflowIF)(nil).Put), auth, item)
}

// Delete mocks base method
func (m *MockWorkflowIF) Delete(auth model.Auth, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", auth, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockWorkflowIFMockRecorder) Delete(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowIF)(nil).Delete), auth, id)
}

// Close mocks base method
func (m *MockWorkflowIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockWorkflowIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkflowIF)(nil).Close))
}

// RegisterExternalNode mocks base method
func (m *MockWorkflowIF) RegisterExternalNode(auth model.Auth, n *externalnode.ExternalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterExternalNode", auth, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterExternalNode indicates an expected call of RegisterExternalNode
func (mr *MockWorkflowIFMockRecorder) RegisterExternalNode(auth, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterExternalNode", reflect.TypeOf((*MockWorkflowIF)(nil).RegisterExternalNode), auth, n)
}

// ListExternalNodes mocks base method
func (m *MockWorkflowIF) ListExternalNodes() []*externalnode.ExternalNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExternalNodes")
	ret0, _ := ret[0].([]*externalnode.ExternalNode)
	return ret0
}

// ListExternalNodes indicates an expected call of ListExternalNodes
func (mr *MockWorkflowIFMockRecorder) ListExternalNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExternalNodes", reflect.TypeOf((*MockWorkflowIF)(nil).ListExternalNodes))
}

// DeleteExternalNode mocks base method
func (m *MockWorkflowIF) DeleteExternalNode(auth model.Auth, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalNode", auth, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalNode indicates an expected call of DeleteExternalNode
func (mr *MockWorkflowIFMockRecorder) DeleteExternalNode(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalNode", reflect.TypeOf((*MockWorkflowIF)(nil).DeleteExternalNode), auth, id)
}

// NodeByName mocks base method
func (m *MockWorkflowIF) NodeByName(auth model.Auth, name string) (*externalnode.ExternalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeByName", auth, name)
	ret0, _ := ret[0].(*externalnode.ExternalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeByName indicates an expected call of NodeByName
func (mr *MockWorkflowIFMockRecorder) NodeByName(auth, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeByName", reflect.TypeOf((*MockWorkflowIF)(nil).NodeByName), auth, name)
}

// QueryFromInstanceID mocks base method
func (m *MockWorkflowIF) QueryFromInstanceID(auth model.Auth, id string) (externalnode.ExternalNodeInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFromInstanceID", auth, id)
	ret0, _ := ret[0].(externalnode.ExternalNodeInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFromInstanceID indicates an expected call of QueryFromInstanceID
func (mr *MockWorkflowIFMockRecorder) QueryFromInstanceID(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFromInstanceID", reflect.TypeOf((*MockWorkflowIF)(nil).QueryFromInstanceID), auth, id)
}

// PutExternalNodeInstance mocks base method
func (m *MockWorkflowIF) PutExternalNodeInstance(auth model.Auth, i *externalnode.ExternalNodeInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutExternalNodeInstance", auth, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutExternalNodeInstance indicates an expected call of PutExternalNodeInstance
func (mr *MockWorkflowIFMockRecorder) PutExternalNodeInstance(auth, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutExternalNodeInstance", reflect.TypeOf((*MockWorkflowIF)(nil).PutExternalNodeInstance), auth, i)
}

// MockExternalNodeIF is a mock of ExternalNodeIF interface
type MockExternalNodeIF struct {
	ctrl     *gomock.Controller
	recorder *MockExternalNodeIFMockRecorder
}

// MockExternalNodeIFMockRecorder is the mock recorder for MockExternalNodeIF
type MockExternalNodeIFMockRecorder struct {
	mock *MockExternalNodeIF
}

// NewMockExternalNodeIF creates a new mock instance
func NewMockExternalNodeIF(ctrl *gomock.Controller) *MockExternalNodeIF {
	mock := &MockExternalNodeIF{ctrl: ctrl}
	mock.recorder = &MockExternalNodeIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExternalNodeIF) EXPECT() *MockExternalNodeIFMockRecorder {
	return m.recorder
}

// RegisterExternalNode mocks base method
func (m *MockExternalNodeIF) RegisterExternalNode(auth model.Auth, n *externalnode.ExternalNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterExternalNode", auth, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterExternalNode indicates an expected call of RegisterExternalNode
func (mr *MockExternalNodeIFMockRecorder) RegisterExternalNode(auth, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterExternalNode", reflect.TypeOf((*MockExternalNodeIF)(nil).RegisterExternalNode), auth, n)
}

// ListExternalNodes mocks base method
func (m *MockExternalNodeIF) ListExternalNodes() []*externalnode.ExternalNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExternalNodes")
	ret0, _ := ret[0].([]*externalnode.ExternalNode)
	return ret0
}

// ListExternalNodes indicates an expected call of ListExternalNodes
func (mr *MockExternalNodeIFMockRecorder) ListExternalNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExternalNodes", reflect.TypeOf((*MockExternalNodeIF)(nil).ListExternalNodes))
}

// DeleteExternalNode mocks base method
func (m *MockExternalNodeIF) DeleteExternalNode(auth model.Auth, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalNode", auth, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalNode indicates an expected call of DeleteExternalNode
func (mr *MockExternalNodeIFMockRecorder) DeleteExternalNode(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalNode", reflect.TypeOf((*MockExternalNodeIF)(nil).DeleteExternalNode), auth, id)
}

// NodeByName mocks base method
func (m *MockExternalNodeIF) NodeByName(auth model.Auth, name string) (*externalnode.ExternalNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeByName", auth, name)
	ret0, _ := ret[0].(*externalnode.ExternalNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeByName indicates an expected call of NodeByName
func (mr *MockExternalNodeIFMockRecorder) NodeByName(auth, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeByName", reflect.TypeOf((*MockExternalNodeIF)(nil).NodeByName), auth, name)
}

// QueryFromInstanceID mocks base method
func (m *MockExternalNodeIF) QueryFromInstanceID(auth model.Auth, id string) (externalnode.ExternalNodeInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFromInstanceID", auth, id)
	ret0, _ := ret[0].(externalnode.ExternalNodeInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFromInstanceID indicates an expected call of QueryFromInstanceID
func (mr *MockExternalNodeIFMockRecorder) QueryFromInstanceID(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFromInstanceID", reflect.TypeOf((*MockExternalNodeIF)(nil).QueryFromInstanceID), auth, id)
}

// PutExternalNodeInstance mocks base method
func (m *MockExternalNodeIF) PutExternalNodeInstance(auth model.Auth, i *externalnode.ExternalNodeInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutExternalNodeInstance", auth, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutExternalNodeInstance indicates an expected call of PutExternalNodeInstance
func (mr *MockExternalNodeIFMockRecorder) PutExternalNodeInstance(auth, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutExternalNodeInstance", reflect.TypeOf((*MockExternalNodeIF)(nil).PutExternalNodeInstance), auth, i)
}

// MockTemplateIF is a mock of TemplateIF interface
type MockTemplateIF struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateIFMockRecorder
}

// MockTemplateIFMockRecorder is the mock recorder for MockTemplateIF
type MockTemplateIFMockRecorder struct {
	mock *MockTemplateIF
}

// NewMockTemplateIF creates a new mock instance
func NewMockTemplateIF(ctrl *gomock.Controller) *MockTemplateIF {
	mock := &MockTemplateIF{ctrl: ctrl}
	mock.recorder = &MockTemplateIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTemplateIF) EXPECT() *MockTemplateIFMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockTemplateIF) List(auth model.Auth, contains string, options storage.Options) ([]*model.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", auth, contains, options)
	ret0, _ := ret[0].([]*model.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockTemplateIFMockRecorder) List(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTemplateIF)(nil).List), auth, contains, options)
}

// Get mocks base method
func (m *MockTemplateIF) Get(auth model.Auth, id string) (*model.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", auth, id)
	ret0, _ := ret[0].(*model.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockTemplateIFMockRecorder) Get(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTemplateIF)(nil).Get), auth, id)
}

// ProvideFileInfoFor mocks base method
func (m *MockTemplateIF) ProvideFileInfoFor(auth model.Auth, id, lang string, fm *file.Meta) (*file.IO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvideFileInfoFor", auth, id, lang, fm)
	ret0, _ := ret[0].(*file.IO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvideFileInfoFor indicates an expected call of ProvideFileInfoFor
func (mr *MockTemplateIFMockRecorder) ProvideFileInfoFor(auth, id, lang, fm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideFileInfoFor", reflect.TypeOf((*MockTemplateIF)(nil).ProvideFileInfoFor), auth, id, lang, fm)
}

// PutVars mocks base method
func (m *MockTemplateIF) PutVars(auth model.Auth, id, lang string, vars []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVars", auth, id, lang, vars)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutVars indicates an expected call of PutVars
func (mr *MockTemplateIFMockRecorder) PutVars(auth, id, lang, vars interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVars", reflect.TypeOf((*MockTemplateIF)(nil).PutVars), auth, id, lang, vars)
}

// GetTemplate mocks base method
func (m *MockTemplateIF) GetTemplate(auth model.Auth, id, lang string) (*file.IO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", auth, id, lang)
	ret0, _ := ret[0].(*file.IO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate
func (mr *MockTemplateIFMockRecorder) GetTemplate(auth, id, lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockTemplateIF)(nil).GetTemplate), auth, id, lang)
}

// DeleteTemplate mocks base method
func (m *MockTemplateIF) DeleteTemplate(auth model.Auth, files storage.FilesIF, id, lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", auth, files, id, lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate
func (mr *MockTemplateIFMockRecorder) DeleteTemplate(auth, files, id, lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockTemplateIF)(nil).DeleteTemplate), auth, files, id, lang)
}

// Put mocks base method
func (m *MockTemplateIF) Put(auth model.Auth, item *model.TemplateItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", auth, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockTemplateIFMockRecorder) Put(auth, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockTemplateIF)(nil).Put), auth, item)
}

// Delete mocks base method
func (m *MockTemplateIF) Delete(auth model.Auth, files storage.FilesIF, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", auth, files, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockTemplateIFMockRecorder) Delete(auth, files, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplateIF)(nil).Delete), auth, files, id)
}

// Vars mocks base method
func (m *MockTemplateIF) Vars(auth model.Auth, contains string, options storage.Options) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vars", auth, contains, options)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vars indicates an expected call of Vars
func (mr *MockTemplateIFMockRecorder) Vars(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vars", reflect.TypeOf((*MockTemplateIF)(nil).Vars), auth, contains, options)
}

// AssetsKey mocks base method
func (m *MockTemplateIF) AssetsKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssetsKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// AssetsKey indicates an expected call of AssetsKey
func (mr *MockTemplateIFMockRecorder) AssetsKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssetsKey", reflect.TypeOf((*MockTemplateIF)(nil).AssetsKey))
}

// Close mocks base method
func (m *MockTemplateIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockTemplateIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTemplateIF)(nil).Close))
}

// MockUserIF is a mock of UserIF interface
type MockUserIF struct {
	ctrl     *gomock.Controller
	recorder *MockUserIFMockRecorder
}

// MockUserIFMockRecorder is the mock recorder for MockUserIF
type MockUserIFMockRecorder struct {
	mock *MockUserIF
}

// NewMockUserIF creates a new mock instance
func NewMockUserIF(ctrl *gomock.Controller) *MockUserIF {
	mock := &MockUserIF{ctrl: ctrl}
	mock.recorder = &MockUserIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserIF) EXPECT() *MockUserIFMockRecorder {
	return m.recorder
}

// GetBaseFilePath mocks base method
func (m *MockUserIF) GetBaseFilePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseFilePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseFilePath indicates an expected call of GetBaseFilePath
func (mr *MockUserIFMockRecorder) GetBaseFilePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseFilePath", reflect.TypeOf((*MockUserIF)(nil).GetBaseFilePath))
}

// Login mocks base method
func (m *MockUserIF) Login(name, pw string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", name, pw)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login
func (mr *MockUserIFMockRecorder) Login(name, pw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserIF)(nil).Login), name, pw)
}

// Count mocks base method
func (m *MockUserIF) Count() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *MockUserIFMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserIF)(nil).Count))
}

// List mocks base method
func (m *MockUserIF) List(auth model.Auth, contains string, options storage.Options) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", auth, contains, options)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockUserIFMockRecorder) List(auth, contains, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserIF)(nil).List), auth, contains, options)
}

// Get mocks base method
func (m *MockUserIF) Get(auth model.Auth, id string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", auth, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUserIFMockRecorder) Get(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserIF)(nil).Get), auth, id)
}

// GetByBCAddress mocks base method
func (m *MockUserIF) GetByBCAddress(bcAddress string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBCAddress", bcAddress)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBCAddress indicates an expected call of GetByBCAddress
func (mr *MockUserIFMockRecorder) GetByBCAddress(bcAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBCAddress", reflect.TypeOf((*MockUserIF)(nil).GetByBCAddress), bcAddress)
}

// GetByEmail mocks base method
func (m *MockUserIF) GetByEmail(email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail
func (mr *MockUserIFMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserIF)(nil).GetByEmail), email)
}

// UpdateEmail mocks base method
func (m *MockUserIF) UpdateEmail(id, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", id, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail
func (mr *MockUserIFMockRecorder) UpdateEmail(id, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockUserIF)(nil).UpdateEmail), id, email)
}

// Put mocks base method
func (m *MockUserIF) Put(auth model.Auth, item *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", auth, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockUserIFMockRecorder) Put(auth, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockUserIF)(nil).Put), auth, item)
}

// PutPw mocks base method
func (m *MockUserIF) PutPw(id, pass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPw", id, pass)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPw indicates an expected call of PutPw
func (mr *MockUserIFMockRecorder) PutPw(id, pass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPw", reflect.TypeOf((*MockUserIF)(nil).PutPw), id, pass)
}

// GetProfilePhoto mocks base method
func (m *MockUserIF) GetProfilePhoto(auth model.Auth, id string, writer io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilePhoto", auth, id, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetProfilePhoto indicates an expected call of GetProfilePhoto
func (mr *MockUserIFMockRecorder) GetProfilePhoto(auth, id, writer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilePhoto", reflect.TypeOf((*MockUserIF)(nil).GetProfilePhoto), auth, id, writer)
}

// PutProfilePhoto mocks base method
func (m *MockUserIF) PutProfilePhoto(auth model.Auth, id string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutProfilePhoto", auth, id, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutProfilePhoto indicates an expected call of PutProfilePhoto
func (mr *MockUserIFMockRecorder) PutProfilePhoto(auth, id, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutProfilePhoto", reflect.TypeOf((*MockUserIF)(nil).PutProfilePhoto), auth, id, reader)
}

// APIKey mocks base method
func (m *MockUserIF) APIKey(key string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIKey", key)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIKey indicates an expected call of APIKey
func (mr *MockUserIFMockRecorder) APIKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIKey", reflect.TypeOf((*MockUserIF)(nil).APIKey), key)
}

// CreateApiKey mocks base method
func (m *MockUserIF) CreateApiKey(auth model.Auth, userId, apiKeyName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", auth, userId, apiKeyName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey
func (mr *MockUserIFMockRecorder) CreateApiKey(auth, userId, apiKeyName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockUserIF)(nil).CreateApiKey), auth, userId, apiKeyName)
}

// DeleteApiKey mocks base method
func (m *MockUserIF) DeleteApiKey(auth model.Auth, userId, hiddenApiKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiKey", auth, userId, hiddenApiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiKey indicates an expected call of DeleteApiKey
func (mr *MockUserIFMockRecorder) DeleteApiKey(auth, userId, hiddenApiKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiKey", reflect.TypeOf((*MockUserIF)(nil).DeleteApiKey), auth, userId, hiddenApiKey)
}

// Close mocks base method
func (m *MockUserIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockUserIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUserIF)(nil).Close))
}

// MockUserDataIF is a mock of UserDataIF interface
type MockUserDataIF struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataIFMockRecorder
}

// MockUserDataIFMockRecorder is the mock recorder for MockUserDataIF
type MockUserDataIFMockRecorder struct {
	mock *MockUserDataIF
}

// NewMockUserDataIF creates a new mock instance
func NewMockUserDataIF(ctrl *gomock.Controller) *MockUserDataIF {
	mock := &MockUserDataIF{ctrl: ctrl}
	mock.recorder = &MockUserDataIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserDataIF) EXPECT() *MockUserDataIFMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockUserDataIF) List(auth model.Auth, contains string, options storage.Options, includeReadGranted bool) ([]*model.UserDataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", auth, contains, options, includeReadGranted)
	ret0, _ := ret[0].([]*model.UserDataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockUserDataIFMockRecorder) List(auth, contains, options, includeReadGranted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserDataIF)(nil).List), auth, contains, options, includeReadGranted)
}

// Delete mocks base method
func (m *MockUserDataIF) Delete(auth model.Auth, files storage.FilesIF, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", auth, files, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUserDataIFMockRecorder) Delete(auth, files, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDataIF)(nil).Delete), auth, files, id)
}

// Get mocks base method
func (m *MockUserDataIF) Get(auth model.Auth, id string) (*model.UserDataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", auth, id)
	ret0, _ := ret[0].(*model.UserDataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUserDataIFMockRecorder) Get(auth, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserDataIF)(nil).Get), auth, id)
}

// GetAllFileInfosOf mocks base method
func (m *MockUserDataIF) GetAllFileInfosOf(ud *model.UserDataItem) []*file.IO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFileInfosOf", ud)
	ret0, _ := ret[0].([]*file.IO)
	return ret0
}

// GetAllFileInfosOf indicates an expected call of GetAllFileInfosOf
func (mr *MockUserDataIFMockRecorder) GetAllFileInfosOf(ud interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFileInfosOf", reflect.TypeOf((*MockUserDataIF)(nil).GetAllFileInfosOf), ud)
}

// GetByWorkflow mocks base method
func (m *MockUserDataIF) GetByWorkflow(auth model.Auth, wf *model.WorkflowItem, finished bool) (*model.UserDataItem, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkflow", auth, wf, finished)
	ret0, _ := ret[0].(*model.UserDataItem)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByWorkflow indicates an expected call of GetByWorkflow
func (mr *MockUserDataIFMockRecorder) GetByWorkflow(auth, wf, finished interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkflow", reflect.TypeOf((*MockUserDataIF)(nil).GetByWorkflow), auth, wf, finished)
}

// GetData mocks base method
func (m *MockUserDataIF) GetData(auth model.Auth, id, dataPath string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", auth, id, dataPath)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData
func (mr *MockUserDataIFMockRecorder) GetData(auth, id, dataPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockUserDataIF)(nil).GetData), auth, id, dataPath)
}

// GetDataAndFiles mocks base method
func (m *MockUserDataIF) GetDataAndFiles(auth model.Auth, id, dataPath string) (interface{}, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataAndFiles", auth, id, dataPath)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDataAndFiles indicates an expected call of GetDataAndFiles
func (mr *MockUserDataIFMockRecorder) GetDataAndFiles(auth, id, dataPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataAndFiles", reflect.TypeOf((*MockUserDataIF)(nil).GetDataAndFiles), auth, id, dataPath)
}

// PutData mocks base method
func (m *MockUserDataIF) PutData(auth model.Auth, id string, dataObj map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutData", auth, id, dataObj)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutData indicates an expected call of PutData
func (mr *MockUserDataIFMockRecorder) PutData(auth, id, dataObj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutData", reflect.TypeOf((*MockUserDataIF)(nil).PutData), auth, id, dataObj)
}

// NewFile mocks base method
func (m *MockUserDataIF) NewFile(auth model.Auth, meta file.Meta) *file.IO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", auth, meta)
	ret0, _ := ret[0].(*file.IO)
	return ret0
}

// NewFile indicates an expected call of NewFile
func (mr *MockUserDataIFMockRecorder) NewFile(auth, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockUserDataIF)(nil).NewFile), auth, meta)
}

// GetDataFile mocks base method
func (m *MockUserDataIF) GetDataFile(auth model.Auth, id, dataPath string) (*file.IO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataFile", auth, id, dataPath)
	ret0, _ := ret[0].(*file.IO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataFile indicates an expected call of GetDataFile
func (mr *MockUserDataIFMockRecorder) GetDataFile(auth, id, dataPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataFile", reflect.TypeOf((*MockUserDataIF)(nil).GetDataFile), auth, id, dataPath)
}

// Put mocks base method
func (m *MockUserDataIF) Put(auth model.Auth, item *model.UserDataItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", auth, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockUserDataIFMockRecorder) Put(auth, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockUserDataIF)(nil).Put), auth, item)
}

// AssetsKey mocks base method
func (m *MockUserDataIF) AssetsKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssetsKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// AssetsKey indicates an expected call of AssetsKey
func (mr *MockUserDataIFMockRecorder) AssetsKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssetsKey", reflect.TypeOf((*MockUserDataIF)(nil).AssetsKey))
}

// Close mocks base method
func (m *MockUserDataIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockUserDataIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUserDataIF)(nil).Close))
}

// MockSignatureRequestsIF is a mock of SignatureRequestsIF interface
type MockSignatureRequestsIF struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureRequestsIFMockRecorder
}

// MockSignatureRequestsIFMockRecorder is the mock recorder for MockSignatureRequestsIF
type MockSignatureRequestsIFMockRecorder struct {
	mock *MockSignatureRequestsIF
}

// NewMockSignatureRequestsIF creates a new mock instance
func NewMockSignatureRequestsIF(ctrl *gomock.Controller) *MockSignatureRequestsIF {
	mock := &MockSignatureRequestsIF{ctrl: ctrl}
	mock.recorder = &MockSignatureRequestsIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSignatureRequestsIF) EXPECT() *MockSignatureRequestsIFMockRecorder {
	return m.recorder
}

// GetBySignatory mocks base method
func (m *MockSignatureRequestsIF) GetBySignatory(ethAddr string) (*[]model.SignatureRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySignatory", ethAddr)
	ret0, _ := ret[0].(*[]model.SignatureRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySignatory indicates an expected call of GetBySignatory
func (mr *MockSignatureRequestsIFMockRecorder) GetBySignatory(ethAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySignatory", reflect.TypeOf((*MockSignatureRequestsIF)(nil).GetBySignatory), ethAddr)
}

// GetByID mocks base method
func (m *MockSignatureRequestsIF) GetByID(docid, docpath string) (*[]model.SignatureRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", docid, docpath)
	ret0, _ := ret[0].(*[]model.SignatureRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockSignatureRequestsIFMockRecorder) GetByID(docid, docpath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSignatureRequestsIF)(nil).GetByID), docid, docpath)
}

// GetByHashAndSigner mocks base method
func (m *MockSignatureRequestsIF) GetByHashAndSigner(hash, signatory string) (*[]model.SignatureRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHashAndSigner", hash, signatory)
	ret0, _ := ret[0].(*[]model.SignatureRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHashAndSigner indicates an expected call of GetByHashAndSigner
func (mr *MockSignatureRequestsIFMockRecorder) GetByHashAndSigner(hash, signatory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHashAndSigner", reflect.TypeOf((*MockSignatureRequestsIF)(nil).GetByHashAndSigner), hash, signatory)
}

// Add mocks base method
func (m *MockSignatureRequestsIF) Add(item *model.SignatureRequestItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockSignatureRequestsIFMockRecorder) Add(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSignatureRequestsIF)(nil).Add), item)
}

// SetRejected mocks base method
func (m *MockSignatureRequestsIF) SetRejected(docid, docpath, signatory string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRejected", docid, docpath, signatory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRejected indicates an expected call of SetRejected
func (mr *MockSignatureRequestsIFMockRecorder) SetRejected(docid, docpath, signatory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRejected", reflect.TypeOf((*MockSignatureRequestsIF)(nil).SetRejected), docid, docpath, signatory)
}

// SetRevoked mocks base method
func (m *MockSignatureRequestsIF) SetRevoked(docid, docpath, signatory string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRevoked", docid, docpath, signatory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRevoked indicates an expected call of SetRevoked
func (mr *MockSignatureRequestsIFMockRecorder) SetRevoked(docid, docpath, signatory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRevoked", reflect.TypeOf((*MockSignatureRequestsIF)(nil).SetRevoked), docid, docpath, signatory)
}

// Close mocks base method
func (m *MockSignatureRequestsIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSignatureRequestsIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSignatureRequestsIF)(nil).Close))
}

// MockWorkflowPaymentsIF is a mock of WorkflowPaymentsIF interface
type MockWorkflowPaymentsIF struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowPaymentsIFMockRecorder
}

// MockWorkflowPaymentsIFMockRecorder is the mock recorder for MockWorkflowPaymentsIF
type MockWorkflowPaymentsIFMockRecorder struct {
	mock *MockWorkflowPaymentsIF
}

// NewMockWorkflowPaymentsIF creates a new mock instance
func NewMockWorkflowPaymentsIF(ctrl *gomock.Controller) *MockWorkflowPaymentsIF {
	mock := &MockWorkflowPaymentsIF{ctrl: ctrl}
	mock.recorder = &MockWorkflowPaymentsIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkflowPaymentsIF) EXPECT() *MockWorkflowPaymentsIFMockRecorder {
	return m.recorder
}

// GetByTxHashAndStatusAndFromEthAddress mocks base method
func (m *MockWorkflowPaymentsIF) GetByTxHashAndStatusAndFromEthAddress(txHash, status, from string) (*model.WorkflowPaymentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTxHashAndStatusAndFromEthAddress", txHash, status, from)
	ret0, _ := ret[0].(*model.WorkflowPaymentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTxHashAndStatusAndFromEthAddress indicates an expected call of GetByTxHashAndStatusAndFromEthAddress
func (mr *MockWorkflowPaymentsIFMockRecorder) GetByTxHashAndStatusAndFromEthAddress(txHash, status, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTxHashAndStatusAndFromEthAddress", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).GetByTxHashAndStatusAndFromEthAddress), txHash, status, from)
}

// Get mocks base method
func (m *MockWorkflowPaymentsIF) Get(paymentId string) (*model.WorkflowPaymentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", paymentId)
	ret0, _ := ret[0].(*model.WorkflowPaymentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockWorkflowPaymentsIFMockRecorder) Get(paymentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Get), paymentId)
}

// ConfirmPayment mocks base method
func (m *MockWorkflowPaymentsIF) ConfirmPayment(txHash, from, to string, xes uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", txHash, from, to, xes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPayment indicates an expected call of ConfirmPayment
func (mr *MockWorkflowPaymentsIFMockRecorder) ConfirmPayment(txHash, from, to, xes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).ConfirmPayment), txHash, from, to, xes)
}

// GetByWorkflowIdAndFromEthAddress mocks base method
func (m *MockWorkflowPaymentsIF) GetByWorkflowIdAndFromEthAddress(workflowID, fromEthAddr string, statuses []string) (*model.WorkflowPaymentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkflowIdAndFromEthAddress", workflowID, fromEthAddr, statuses)
	ret0, _ := ret[0].(*model.WorkflowPaymentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkflowIdAndFromEthAddress indicates an expected call of GetByWorkflowIdAndFromEthAddress
func (mr *MockWorkflowPaymentsIFMockRecorder) GetByWorkflowIdAndFromEthAddress(workflowID, fromEthAddr, statuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkflowIdAndFromEthAddress", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).GetByWorkflowIdAndFromEthAddress), workflowID, fromEthAddr, statuses)
}

// SetAbandonedToTimeoutBeforeTime mocks base method
func (m *MockWorkflowPaymentsIF) SetAbandonedToTimeoutBeforeTime(beforeTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAbandonedToTimeoutBeforeTime", beforeTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAbandonedToTimeoutBeforeTime indicates an expected call of SetAbandonedToTimeoutBeforeTime
func (mr *MockWorkflowPaymentsIFMockRecorder) SetAbandonedToTimeoutBeforeTime(beforeTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAbandonedToTimeoutBeforeTime", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).SetAbandonedToTimeoutBeforeTime), beforeTime)
}

// Save mocks base method
func (m *MockWorkflowPaymentsIF) Save(item *model.WorkflowPaymentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockWorkflowPaymentsIFMockRecorder) Save(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Save), item)
}

// Update mocks base method
func (m *MockWorkflowPaymentsIF) Update(paymentId, status, txHash, from string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", paymentId, status, txHash, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockWorkflowPaymentsIFMockRecorder) Update(paymentId, status, txHash, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Update), paymentId, status, txHash, from)
}

// Cancel mocks base method
func (m *MockWorkflowPaymentsIF) Cancel(paymentId, from string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", paymentId, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel
func (mr *MockWorkflowPaymentsIFMockRecorder) Cancel(paymentId, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Cancel), paymentId, from)
}

// Redeem mocks base method
func (m *MockWorkflowPaymentsIF) Redeem(workflowId, from string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", workflowId, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redeem indicates an expected call of Redeem
func (mr *MockWorkflowPaymentsIFMockRecorder) Redeem(workflowId, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Redeem), workflowId, from)
}

// Delete mocks base method
func (m *MockWorkflowPaymentsIF) Delete(paymentId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", paymentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockWorkflowPaymentsIFMockRecorder) Delete(paymentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Delete), paymentId)
}

// Remove mocks base method
func (m *MockWorkflowPaymentsIF) Remove(payment *model.WorkflowPaymentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (mr *MockWorkflowPaymentsIFMockRecorder) Remove(payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Remove), payment)
}

// All mocks base method
func (m *MockWorkflowPaymentsIF) All() ([]*model.WorkflowPaymentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].([]*model.WorkflowPaymentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All
func (mr *MockWorkflowPaymentsIFMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).All))
}

// Close mocks base method
func (m *MockWorkflowPaymentsIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockWorkflowPaymentsIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkflowPaymentsIF)(nil).Close))
}

// MockFilesIF is a mock of FilesIF interface
type MockFilesIF struct {
	ctrl     *gomock.Controller
	recorder *MockFilesIFMockRecorder
}

// MockFilesIFMockRecorder is the mock recorder for MockFilesIF
type MockFilesIFMockRecorder struct {
	mock *MockFilesIF
}

// NewMockFilesIF creates a new mock instance
func NewMockFilesIF(ctrl *gomock.Controller) *MockFilesIF {
	mock := &MockFilesIF{ctrl: ctrl}
	mock.recorder = &MockFilesIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFilesIF) EXPECT() *MockFilesIFMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockFilesIF) Read(path string, w io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read
func (mr *MockFilesIFMockRecorder) Read(path, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFilesIF)(nil).Read), path, w)
}

// Write mocks base method
func (m *MockFilesIF) Write(path string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", path, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockFilesIFMockRecorder) Write(path, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFilesIF)(nil).Write), path, r)
}

// Exists mocks base method
func (m *MockFilesIF) Exists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockFilesIFMockRecorder) Exists(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFilesIF)(nil).Exists), path)
}

// Delete mocks base method
func (m *MockFilesIF) Delete(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockFilesIFMockRecorder) Delete(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFilesIF)(nil).Delete), path)
}

// Close mocks base method
func (m *MockFilesIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockFilesIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFilesIF)(nil).Close))
}

// MockSessionIF is a mock of SessionIF interface
type MockSessionIF struct {
	ctrl     *gomock.Controller
	recorder *MockSessionIFMockRecorder
}

// MockSessionIFMockRecorder is the mock recorder for MockSessionIF
type MockSessionIFMockRecorder struct {
	mock *MockSessionIF
}

// NewMockSessionIF creates a new mock instance
func NewMockSessionIF(ctrl *gomock.Controller) *MockSessionIF {
	mock := &MockSessionIF{ctrl: ctrl}
	mock.recorder = &MockSessionIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionIF) EXPECT() *MockSessionIFMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockSessionIF) Get(sid string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", sid)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockSessionIFMockRecorder) Get(sid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionIF)(nil).Get), sid)
}

// Put mocks base method
func (m *MockSessionIF) Put(s *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockSessionIFMockRecorder) Put(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSessionIF)(nil).Put), s)
}

// Delete mocks base method
func (m *MockSessionIF) Delete(s *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockSessionIFMockRecorder) Delete(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionIF)(nil).Delete), s)
}

// GetTokenRequest mocks base method
func (m *MockSessionIF) GetTokenRequest(t model.TokenType, id string) (*model.TokenRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenRequest", t, id)
	ret0, _ := ret[0].(*model.TokenRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenRequest indicates an expected call of GetTokenRequest
func (mr *MockSessionIFMockRecorder) GetTokenRequest(t, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenRequest", reflect.TypeOf((*MockSessionIF)(nil).GetTokenRequest), t, id)
}

// PutTokenRequest mocks base method
func (m *MockSessionIF) PutTokenRequest(r *model.TokenRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTokenRequest", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutTokenRequest indicates an expected call of PutTokenRequest
func (mr *MockSessionIFMockRecorder) PutTokenRequest(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTokenRequest", reflect.TypeOf((*MockSessionIF)(nil).PutTokenRequest), r)
}

// DeleteTokenRequest mocks base method
func (m *MockSessionIF) DeleteTokenRequest(r *model.TokenRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokenRequest", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokenRequest indicates an expected call of DeleteTokenRequest
func (mr *MockSessionIFMockRecorder) DeleteTokenRequest(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokenRequest", reflect.TypeOf((*MockSessionIF)(nil).DeleteTokenRequest), r)
}

// GetValue mocks base method
func (m *MockSessionIF) GetValue(key string, v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", key, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetValue indicates an expected call of GetValue
func (mr *MockSessionIFMockRecorder) GetValue(key, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockSessionIF)(nil).GetValue), key, v)
}

// PutValue mocks base method
func (m *MockSessionIF) PutValue(key string, v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutValue", key, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutValue indicates an expected call of PutValue
func (mr *MockSessionIFMockRecorder) PutValue(key, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutValue", reflect.TypeOf((*MockSessionIF)(nil).PutValue), key, v)
}

// DeleteValue mocks base method
func (m *MockSessionIF) DeleteValue(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteValue", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteValue indicates an expected call of DeleteValue
func (mr *MockSessionIFMockRecorder) DeleteValue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteValue", reflect.TypeOf((*MockSessionIF)(nil).DeleteValue), key)
}

// Close mocks base method
func (m *MockSessionIF) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSessionIFMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessionIF)(nil).Close))
}
